### ISSUE TITLE
Gracefully failback to `pysmt` when `ortools` not available

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwavebinarycsp#61]
On 64-bit OS and 32-bit Python we still try to install `penaltymodel-mip` (which uses `ortools`), instead of `penaltymodel-maxgap`.

**Comment by randomir** [comment]
An alternative to automated fallback is adding a possibility of "manual override": to e.g. prefer `penaltymodel-maxgap`.

**Comment by randomir** [comment]
Default "extra" would solve this problem. Unfortunately, it's [far from being available](https://github.com/pypa/setuptools/issues/1139).

**Comment by arcondello** [comment]
As of version [penaltymodel 1.0.0](https://github.com/dwavesystems/penaltymodel/releases/tag/1.0.0) penaltymodel only has one factory that uses SciPy.
