### ISSUE TITLE
Check that stitch cascades through each penaltymodel

### ISSUE THREAD

**Issue by m3ller** [dwavesystems/dwavebinarycsp#72]
**Application**
The stitch function generates a BQM's penaltymodel by cascading thorough Cache, LP, MIP, and finally, MaxGap. 
- Make a test to verify that this cascade is happening in the expected order. 
- Make sure that the simpler BQMs are being caught earlier in the cascade (i.e. a problem that can be solved with LP should not be able to cascade down to MaxGap).

**Proposed Solution**
Make problems of varying "difficulty" so that we can observe that the proper penaltymodels are catching said problems. (Ex. LP should be able to catch an OR-gate, but not an XOR-gate. XOR-gate needs auxiliary variables and LP does not handle that, therefore the problem should be passed to MIP.)

**Comment by arcondello** [comment]
As of version [penaltymodel 1.0.0](https://github.com/dwavesystems/penaltymodel/releases/tag/1.0.0) penaltymodel only has one factory that uses SciPy.
